TG-1074 Maintenance - Reorganize core project files to use the src folder pattern
20tab/react-continuous-delivery pull request #34
Opened 2024-01-23 17:28 UTC by lucaspinosi

By introducing a `./src` folder, this PR improves the project structure by separating the core frontend files from the project configuration files

2024-01-23 17:29 UTC, niccolomineo approved these changes

2024-01-26 09:45 UTC, pauloxnet approved these changes

2024-01-26 09:50 UTC, trottomv requested changes
Have the various `mounts` on Docker Compose and `COPY` on Dockerfile(s) been verified?

2024-01-26 11:14 UTC, trottomv approved these changes

2024-01-26 11:41 UTC, merged