TG-1126 Maintenance - Generate a robot.txt per environment at build time
20tab/react-continuous-delivery pull request #41
Opened 2024-02-21 10:22 UTC by lucaspinosi

Taiga US details: [#1126](https://taiga.20tab.com/project/20tab-20tab_project/us/1126?milestone=1410)

2024-02-21 16:30 UTC, daniele20tab commented on {{cookiecutter.project_dirname}}/.gitignore
> +*/plublic/robot.txt
Typo?

2024-02-26 14:50 UTC, trottomv requested changes

2024-02-26 14:50 UTC, trottomv commented on {{cookiecutter.project_dirname}}/.gitignore
> +next-env.d.ts
```suggestion
next-env.d.ts

```

2024-02-26 14:50 UTC, trottomv commented on {{cookiecutter.project_dirname}}/docker/remote.Dockerfile
> +RUN rm -rf public/robots
```suggestion
RUN rm -rf public/robots/
```

2024-02-27 08:10 UTC, daniele20tab approved these changes

2024-02-27 08:13 UTC, trottomv requested changes

2024-02-27 08:13 UTC, trottomv commented on {{cookiecutter.project_dirname}}/.gitlab-ci.yml
> +    - job: can-i-deploy_staging
```suggestion
    - job: can-i-deploy_staging
```

2024-02-27 08:38 UTC, trottomv requested changes

2024-02-27 08:38 UTC, trottomv commented on {{cookiecutter.project_dirname}}/.gitlab-ci.yml
> +      --args-${CI_ENVIRONMENT_NAME}
```suggestion
      --args-${REACT_ENVIRONMENT}
```

2024-02-27 08:43 UTC, trottomv requested changes

2024-02-27 08:43 UTC, trottomv commented on {{cookiecutter.project_dirname}}/.gitlab-ci.yml
> +      --args-${CI_ENVIRONMENT_NAME}
```suggestion
      --build-arg REACT_ENVIRONMENT
```

2024-02-27 09:14 UTC, trottomv approved these changes

2024-02-27 09:27 UTC, pauloxnet approved these changes

2024-02-27 11:57 UTC, trottomv commented on {{cookiecutter.project_dirname}}/docker/local.Dockerfile
> +CMD yarn dev
```suggestion
CMD yarn start
```

2026-04-28 06:59 UTC, closed without merging